<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: MarketDataFeedV3.proto

namespace Com\Upstox\Marketdatafeederv3udapi\Rpc\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>com.upstox.marketdatafeederv3udapi.rpc.proto.FeedResponse</code>
 */
class FeedResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.com.upstox.marketdatafeederv3udapi.rpc.proto.Type type = 1;</code>
     */
    protected $type = 0;
    /**
     * Generated from protobuf field <code>map<string, .com.upstox.marketdatafeederv3udapi.rpc.proto.Feed> feeds = 2;</code>
     */
    private $feeds;
    /**
     * Generated from protobuf field <code>int64 currentTs = 3;</code>
     */
    protected $currentTs = 0;
    /**
     * Generated from protobuf field <code>.com.upstox.marketdatafeederv3udapi.rpc.proto.MarketInfo marketInfo = 4;</code>
     */
    protected $marketInfo = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $type
     *     @type array|\Google\Protobuf\Internal\MapField $feeds
     *     @type int|string $currentTs
     *     @type \Com\Upstox\Marketdatafeederv3udapi\Rpc\Proto\MarketInfo $marketInfo
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\MarketDataFeedV3::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.com.upstox.marketdatafeederv3udapi.rpc.proto.Type type = 1;</code>
     * @return int
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Generated from protobuf field <code>.com.upstox.marketdatafeederv3udapi.rpc.proto.Type type = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkEnum($var, \Com\Upstox\Marketdatafeederv3udapi\Rpc\Proto\Type::class);
        $this->type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>map<string, .com.upstox.marketdatafeederv3udapi.rpc.proto.Feed> feeds = 2;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getFeeds()
    {
        return $this->feeds;
    }

    /**
     * Generated from protobuf field <code>map<string, .com.upstox.marketdatafeederv3udapi.rpc.proto.Feed> feeds = 2;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setFeeds($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::MESSAGE, \Com\Upstox\Marketdatafeederv3udapi\Rpc\Proto\Feed::class);
        $this->feeds = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 currentTs = 3;</code>
     * @return int|string
     */
    public function getCurrentTs()
    {
        return $this->currentTs;
    }

    /**
     * Generated from protobuf field <code>int64 currentTs = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCurrentTs($var)
    {
        GPBUtil::checkInt64($var);
        $this->currentTs = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.com.upstox.marketdatafeederv3udapi.rpc.proto.MarketInfo marketInfo = 4;</code>
     * @return \Com\Upstox\Marketdatafeederv3udapi\Rpc\Proto\MarketInfo|null
     */
    public function getMarketInfo()
    {
        return $this->marketInfo;
    }

    public function hasMarketInfo()
    {
        return isset($this->marketInfo);
    }

    public function clearMarketInfo()
    {
        unset($this->marketInfo);
    }

    /**
     * Generated from protobuf field <code>.com.upstox.marketdatafeederv3udapi.rpc.proto.MarketInfo marketInfo = 4;</code>
     * @param \Com\Upstox\Marketdatafeederv3udapi\Rpc\Proto\MarketInfo $var
     * @return $this
     */
    public function setMarketInfo($var)
    {
        GPBUtil::checkMessage($var, \Com\Upstox\Marketdatafeederv3udapi\Rpc\Proto\MarketInfo::class);
        $this->marketInfo = $var;

        return $this;
    }

}

