<?php
/**
 * CashMarginUsed
 *
 * PHP version 5
 *
 * @category Class
 * @package  Upstox\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * OpenAPI definition
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.66
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Upstox\Client\Model;

use \ArrayAccess;
use \Upstox\Client\ObjectSerializer;

/**
 * CashMarginUsed Class Doc Comment
 *
 * @category Class
 * @package  Upstox\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class CashMarginUsed implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'CashMarginUsed';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'total' => '',
        'mtf' => '',
        'loss' => '\Upstox\Client\Model\Loss',
        'span_exposure' => '',
        'cash_margin_var_elm' => '',
        'premium_present' => '',
        'delivery_margin' => '\Upstox\Client\Model\DeliveryMargin'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'total' => 'float',
        'mtf' => 'float',
        'loss' => null,
        'span_exposure' => 'float',
        'cash_margin_var_elm' => 'float',
        'premium_present' => 'float',
        'delivery_margin' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'total' => 'total',
        'mtf' => 'mtf',
        'loss' => 'loss',
        'span_exposure' => 'span_exposure',
        'cash_margin_var_elm' => 'cash_margin_var_elm',
        'premium_present' => 'premium_present',
        'delivery_margin' => 'delivery_margin'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'total' => 'setTotal',
        'mtf' => 'setMtf',
        'loss' => 'setLoss',
        'span_exposure' => 'setSpanExposure',
        'cash_margin_var_elm' => 'setCashMarginVarElm',
        'premium_present' => 'setPremiumPresent',
        'delivery_margin' => 'setDeliveryMargin'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'total' => 'getTotal',
        'mtf' => 'getMtf',
        'loss' => 'getLoss',
        'span_exposure' => 'getSpanExposure',
        'cash_margin_var_elm' => 'getCashMarginVarElm',
        'premium_present' => 'getPremiumPresent',
        'delivery_margin' => 'getDeliveryMargin'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }



    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['total'] = isset($data['total']) ? $data['total'] : null;
        $this->container['mtf'] = isset($data['mtf']) ? $data['mtf'] : null;
        $this->container['loss'] = isset($data['loss']) ? $data['loss'] : null;
        $this->container['span_exposure'] = isset($data['span_exposure']) ? $data['span_exposure'] : null;
        $this->container['cash_margin_var_elm'] = isset($data['cash_margin_var_elm']) ? $data['cash_margin_var_elm'] : null;
        $this->container['premium_present'] = isset($data['premium_present']) ? $data['premium_present'] : null;
        $this->container['delivery_margin'] = isset($data['delivery_margin']) ? $data['delivery_margin'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets total
     *
     * @return 
     */
    public function getTotal()
    {
        return $this->container['total'];
    }

    /**
     * Sets total
     *
     * @param  $total total
     *
     * @return $this
     */
    public function setTotal($total)
    {
        $this->container['total'] = $total;

        return $this;
    }

    /**
     * Gets mtf
     *
     * @return 
     */
    public function getMtf()
    {
        return $this->container['mtf'];
    }

    /**
     * Sets mtf
     *
     * @param  $mtf mtf
     *
     * @return $this
     */
    public function setMtf($mtf)
    {
        $this->container['mtf'] = $mtf;

        return $this;
    }

    /**
     * Gets loss
     *
     * @return \Upstox\Client\Model\Loss
     */
    public function getLoss()
    {
        return $this->container['loss'];
    }

    /**
     * Sets loss
     *
     * @param \Upstox\Client\Model\Loss $loss loss
     *
     * @return $this
     */
    public function setLoss($loss)
    {
        $this->container['loss'] = $loss;

        return $this;
    }

    /**
     * Gets span_exposure
     *
     * @return 
     */
    public function getSpanExposure()
    {
        return $this->container['span_exposure'];
    }

    /**
     * Sets span_exposure
     *
     * @param  $span_exposure span_exposure
     *
     * @return $this
     */
    public function setSpanExposure($span_exposure)
    {
        $this->container['span_exposure'] = $span_exposure;

        return $this;
    }

    /**
     * Gets cash_margin_var_elm
     *
     * @return 
     */
    public function getCashMarginVarElm()
    {
        return $this->container['cash_margin_var_elm'];
    }

    /**
     * Sets cash_margin_var_elm
     *
     * @param  $cash_margin_var_elm cash_margin_var_elm
     *
     * @return $this
     */
    public function setCashMarginVarElm($cash_margin_var_elm)
    {
        $this->container['cash_margin_var_elm'] = $cash_margin_var_elm;

        return $this;
    }

    /**
     * Gets premium_present
     *
     * @return 
     */
    public function getPremiumPresent()
    {
        return $this->container['premium_present'];
    }

    /**
     * Sets premium_present
     *
     * @param  $premium_present premium_present
     *
     * @return $this
     */
    public function setPremiumPresent($premium_present)
    {
        $this->container['premium_present'] = $premium_present;

        return $this;
    }

    /**
     * Gets delivery_margin
     *
     * @return \Upstox\Client\Model\DeliveryMargin
     */
    public function getDeliveryMargin()
    {
        return $this->container['delivery_margin'];
    }

    /**
     * Sets delivery_margin
     *
     * @param \Upstox\Client\Model\DeliveryMargin $delivery_margin delivery_margin
     *
     * @return $this
     */
    public function setDeliveryMargin($delivery_margin)
    {
        $this->container['delivery_margin'] = $delivery_margin;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
