<?php
/**
 * IpoTimeline
 *
 * PHP version 5
 *
 * @category Class
 * @package  Upstox\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * OpenAPI definition
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.79
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Upstox\Client\Model;

use \ArrayAccess;
use \Upstox\Client\ObjectSerializer;

/**
 * IpoTimeline Class Doc Comment
 *
 * @category Class
 * @package  Upstox\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class IpoTimeline implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'IpoTimeline';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'pre_apply_start_date' => 'string',
        'application_start_date' => 'string',
        'application_end_date' => 'string',
        'allotment_start_date' => 'string',
        'allotment_date' => 'string',
        'refund_initiation_date' => 'string',
        'listing_date' => 'string',
        'mandate_end_date' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'pre_apply_start_date' => null,
        'application_start_date' => null,
        'application_end_date' => null,
        'allotment_start_date' => null,
        'allotment_date' => null,
        'refund_initiation_date' => null,
        'listing_date' => null,
        'mandate_end_date' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'pre_apply_start_date' => 'pre_apply_start_date',
        'application_start_date' => 'application_start_date',
        'application_end_date' => 'application_end_date',
        'allotment_start_date' => 'allotment_start_date',
        'allotment_date' => 'allotment_date',
        'refund_initiation_date' => 'refund_initiation_date',
        'listing_date' => 'listing_date',
        'mandate_end_date' => 'mandate_end_date'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'pre_apply_start_date' => 'setPreApplyStartDate',
        'application_start_date' => 'setApplicationStartDate',
        'application_end_date' => 'setApplicationEndDate',
        'allotment_start_date' => 'setAllotmentStartDate',
        'allotment_date' => 'setAllotmentDate',
        'refund_initiation_date' => 'setRefundInitiationDate',
        'listing_date' => 'setListingDate',
        'mandate_end_date' => 'setMandateEndDate'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'pre_apply_start_date' => 'getPreApplyStartDate',
        'application_start_date' => 'getApplicationStartDate',
        'application_end_date' => 'getApplicationEndDate',
        'allotment_start_date' => 'getAllotmentStartDate',
        'allotment_date' => 'getAllotmentDate',
        'refund_initiation_date' => 'getRefundInitiationDate',
        'listing_date' => 'getListingDate',
        'mandate_end_date' => 'getMandateEndDate'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }



    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['pre_apply_start_date'] = isset($data['pre_apply_start_date']) ? $data['pre_apply_start_date'] : null;
        $this->container['application_start_date'] = isset($data['application_start_date']) ? $data['application_start_date'] : null;
        $this->container['application_end_date'] = isset($data['application_end_date']) ? $data['application_end_date'] : null;
        $this->container['allotment_start_date'] = isset($data['allotment_start_date']) ? $data['allotment_start_date'] : null;
        $this->container['allotment_date'] = isset($data['allotment_date']) ? $data['allotment_date'] : null;
        $this->container['refund_initiation_date'] = isset($data['refund_initiation_date']) ? $data['refund_initiation_date'] : null;
        $this->container['listing_date'] = isset($data['listing_date']) ? $data['listing_date'] : null;
        $this->container['mandate_end_date'] = isset($data['mandate_end_date']) ? $data['mandate_end_date'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets pre_apply_start_date
     *
     * @return 
     */
    public function getPreApplyStartDate()
    {
        return $this->container['pre_apply_start_date'];
    }

    /**
     * Sets pre_apply_start_date
     *
     * @param  $pre_apply_start_date pre_apply_start_date
     *
     * @return $this
     */
    public function setPreApplyStartDate($pre_apply_start_date)
    {
        $this->container['pre_apply_start_date'] = $pre_apply_start_date;

        return $this;
    }

    /**
     * Gets application_start_date
     *
     * @return 
     */
    public function getApplicationStartDate()
    {
        return $this->container['application_start_date'];
    }

    /**
     * Sets application_start_date
     *
     * @param  $application_start_date application_start_date
     *
     * @return $this
     */
    public function setApplicationStartDate($application_start_date)
    {
        $this->container['application_start_date'] = $application_start_date;

        return $this;
    }

    /**
     * Gets application_end_date
     *
     * @return 
     */
    public function getApplicationEndDate()
    {
        return $this->container['application_end_date'];
    }

    /**
     * Sets application_end_date
     *
     * @param  $application_end_date application_end_date
     *
     * @return $this
     */
    public function setApplicationEndDate($application_end_date)
    {
        $this->container['application_end_date'] = $application_end_date;

        return $this;
    }

    /**
     * Gets allotment_start_date
     *
     * @return 
     */
    public function getAllotmentStartDate()
    {
        return $this->container['allotment_start_date'];
    }

    /**
     * Sets allotment_start_date
     *
     * @param  $allotment_start_date allotment_start_date
     *
     * @return $this
     */
    public function setAllotmentStartDate($allotment_start_date)
    {
        $this->container['allotment_start_date'] = $allotment_start_date;

        return $this;
    }

    /**
     * Gets allotment_date
     *
     * @return 
     */
    public function getAllotmentDate()
    {
        return $this->container['allotment_date'];
    }

    /**
     * Sets allotment_date
     *
     * @param  $allotment_date allotment_date
     *
     * @return $this
     */
    public function setAllotmentDate($allotment_date)
    {
        $this->container['allotment_date'] = $allotment_date;

        return $this;
    }

    /**
     * Gets refund_initiation_date
     *
     * @return 
     */
    public function getRefundInitiationDate()
    {
        return $this->container['refund_initiation_date'];
    }

    /**
     * Sets refund_initiation_date
     *
     * @param  $refund_initiation_date refund_initiation_date
     *
     * @return $this
     */
    public function setRefundInitiationDate($refund_initiation_date)
    {
        $this->container['refund_initiation_date'] = $refund_initiation_date;

        return $this;
    }

    /**
     * Gets listing_date
     *
     * @return 
     */
    public function getListingDate()
    {
        return $this->container['listing_date'];
    }

    /**
     * Sets listing_date
     *
     * @param  $listing_date listing_date
     *
     * @return $this
     */
    public function setListingDate($listing_date)
    {
        $this->container['listing_date'] = $listing_date;

        return $this;
    }

    /**
     * Gets mandate_end_date
     *
     * @return 
     */
    public function getMandateEndDate()
    {
        return $this->container['mandate_end_date'];
    }

    /**
     * Sets mandate_end_date
     *
     * @param  $mandate_end_date mandate_end_date
     *
     * @return $this
     */
    public function setMandateEndDate($mandate_end_date)
    {
        $this->container['mandate_end_date'] = $mandate_end_date;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
