<?php
/**
 * MultiOrderErrorTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Upstox\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * OpenAPI definition
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.62
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Upstox\Client;

use PHPUnit\Framework\TestCase;

/**
 * MultiOrderErrorTest Class Doc Comment
 *
 * @category    Class
 * @description Error details for multi order request
 * @package     Upstox\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class MultiOrderErrorTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "MultiOrderError"
     */
    public function testMultiOrderError()
    {
    }

    /**
     * Test attribute "error_code"
     */
    public function testPropertyErrorCode()
    {
    }

    /**
     * Test attribute "message"
     */
    public function testPropertyMessage()
    {
    }

    /**
     * Test attribute "property_path"
     */
    public function testPropertyPropertyPath()
    {
    }

    /**
     * Test attribute "invalid_value"
     */
    public function testPropertyInvalidValue()
    {
    }

    /**
     * Test attribute "error_code"
     */
    public function testPropertyErrorCode()
    {
    }

    /**
     * Test attribute "property_path"
     */
    public function testPropertyPropertyPath()
    {
    }

    /**
     * Test attribute "invalid_value"
     */
    public function testPropertyInvalidValue()
    {
    }

    /**
     * Test attribute "correlation_id"
     */
    public function testPropertyCorrelationId()
    {
    }
}
