<?php
/**
 * OptionStrikeDataTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Upstox\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * OpenAPI definition
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.54
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Upstox\Client;

use PHPUnit\Framework\TestCase;

/**
 * OptionStrikeDataTest Class Doc Comment
 *
 * @category    Class
 * @description Response data for option chain data
 * @package     Upstox\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class OptionStrikeDataTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "OptionStrikeData"
     */
    public function testOptionStrikeData()
    {
    }

    /**
     * Test attribute "expiry"
     */
    public function testPropertyExpiry()
    {
    }

    /**
     * Test attribute "pcr"
     */
    public function testPropertyPcr()
    {
    }

    /**
     * Test attribute "strike_price"
     */
    public function testPropertyStrikePrice()
    {
    }

    /**
     * Test attribute "underlying_key"
     */
    public function testPropertyUnderlyingKey()
    {
    }

    /**
     * Test attribute "underlying_spot_price"
     */
    public function testPropertyUnderlyingSpotPrice()
    {
    }

    /**
     * Test attribute "call_options"
     */
    public function testPropertyCallOptions()
    {
    }

    /**
     * Test attribute "put_options"
     */
    public function testPropertyPutOptions()
    {
    }
}
