<?php
/**
 * TradeHistoryResponsePageDataTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Upstox\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * OpenAPI definition
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.54
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Upstox\Client;

use PHPUnit\Framework\TestCase;

/**
 * TradeHistoryResponsePageDataTest Class Doc Comment
 *
 * @category    Class
 * @description TradeHistoryResponsePageData
 * @package     Upstox\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class TradeHistoryResponsePageDataTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "TradeHistoryResponsePageData"
     */
    public function testTradeHistoryResponsePageData()
    {
    }

    /**
     * Test attribute "page_number"
     */
    public function testPropertyPageNumber()
    {
    }

    /**
     * Test attribute "page_size"
     */
    public function testPropertyPageSize()
    {
    }

    /**
     * Test attribute "total_records"
     */
    public function testPropertyTotalRecords()
    {
    }

    /**
     * Test attribute "total_pages"
     */
    public function testPropertyTotalPages()
    {
    }
}
